### ISSUE TITLE
What should I do to run denoise using this docker image?

### ISSUE THREAD

**Issue by Zhenyi-Liu** [OpenImageDenoise/docker-images#1]
I build the ubuntu docker, but I am not sure how I can use this docker image for denoising, and I ran run_docker.sh, I found there is no bin under opt/intel/ dir.

**Comment by atafra** [comment]
These docker images are not for running the denoiser but for building the library. To try the example `denoise` application, please download the binary package from: https://openimagedenoise.github.io/downloads.html
